### ISSUE TITLE
Index out of bounds panic

### ISSUE THREAD

**Issue by radare** [kondrak/disasm6502#1]
As long as this crate aims to be used as a library it shouldnt panic. The following line shows that it is passing the bytes buffer without the length:

https://github.com/kondrak/disasm6502/blob/master/src/lib.rs#L104

for this reason when disassembling vec![0x90] results in a panic at line instruction.rs#333

this is the error i get:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/disasm6502-0.2.0/src/instruction.rs:333
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```

**Comment by kondrak** [comment]
Thanks for catching this! Currently function input expects the array to contain "proper" instruction list (so with 0x90 it's missing an operand, hence the panic), I'll add more sanity checks.

**Comment by emoon** [comment]
Yeah never expect anything of the data that comes in. A user can send any random memory.

**Comment by kondrak** [comment]
I'll add a new error type to handle cases like this. Certain instructions must have an operand, otherwise they can't be decoded properly.

**Comment by emoon** [comment]
Sure but if they can't be decoded you have to emit something else instead. Different assemblers does it diffidently but some emits data statements (like `db $ff`) when instructions can't be decoded.

**Comment by kondrak** [comment]
Think I'll just throw in some "???" instruction instead since I'm not sure what kind of data users will want to work with and this is enough to give an indication that decoding process went wrong.

**Comment by emoon** [comment]
Might be interesting to look at how other disassemblers do it (esp for 6502) but maybe @radare has some suggestions here as well.

**Comment by kondrak** [comment]
I had a very quick look at some online disassemblers for 6502 and what they seem to do is just set the operand to 0x00 if it can't be fetched.

**Comment by radare** [comment]
imho we should split the logic behind the disassembler and the high level disassembler that interprets that information and hints with labels, data types and other stuff, in r2 i use many disassemblers as backends and i implement all this logic on top of that, to avoid duplicates. this can be also done in another rust crate if needed to work in a generic way with multiple disassembler engines.

so i don’t care too much about the textual representation for invalid instructions (or missing bytes provided)

thanks

**Comment by kondrak** [comment]
Final formatting is done by the example application (I just provide some default display traits for the Instruction type), so you're free to output it in your own, custom way. 
After a bit more research it seems that few disassemblers out there handle bad input cases such as the one you provided, so the least intrusive way to solve it is to just default to a 0x00 operand if an out-of-bound array read is to be performed.

**Comment by radare** [comment]
Thanks! works like a charm! will publish my code soon

**Comment by kondrak** [comment]
Great! Hope you find this crate useful!

**Comment by radare** [comment]
see https://github.com/radare/radare2-extras/commit/3d59572c78683d66569c4b341145f361e99e1a3f

my rust is very primitive yet, and but i think we can improve both projects if we do some iterations here.. thanks!

**Comment by emoon** [comment]
@radare Just a small comment on your code. You really want to use `#[repr(C)]` on your Rust structs that should match a C API used from C(++). The Rust compiler is allowed to re-arrange struct members if it desires and `#[repr(C)]` will prevent that and and follow the C standard. See https://doc.rust-lang.org/book/ffi.html#interoperability-with-foreign-code for more info.

**Comment by radare** [comment]
thanks! i have changed that as well as used Option for the function pointers. i think i can remove a bunch of casts and split the logic into different crates (r2, rasm, …) but it’s good to hear feedback from others when starting to learn a new language.

**Comment by emoon** [comment]
Np!

What I would recommend later is that you consider doing a wrapper on top of C API and when a user is going to implement a plugin using Rust there is a more "rustified" API. 

For example backend plugins for ProDBG needs to implement plugins for a C API like this.

https://github.com/emoon/ProDBG/blob/master/api/rust/prodbg/src/backend.rs#L92

But the Rust plugins can use the Backend trait https://github.com/emoon/ProDBG/blob/master/api/rust/prodbg/src/backend.rs#L81 to implement a plugin which gives you a nicer to use API.

And then I have a macro here https://github.com/emoon/ProDBG/blob/master/api/rust/prodbg/src/backend.rs#L150 that hides some of the setup.

A very simple plugin would look something like this (un-tested but it's an idea)

```Rust
pub struct MyBackend {
  foo: i32;
}

impl prodbg::Backend for MyBackend {
  fn update(&mut self, action: i32, reader: &mut Reader, writer: &mut Writer) -> DebugState {
     ...
  }
}

define_backend_plugin!(PLUGIN, b"My Cool Backend\0", MyBackend);
```
